=== tfonrouge/MOODB/src/moodbxml.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        elementFormDefault="qualified"
        targetNamespace="http://fonrouge.tech/MOODB"
        xmlns="http://fonrouge.tech/MOODB"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Table" type="TableType"/>
    <xs:complexType name="TableType">
        <xs:sequence>
            <xs:element name="Fields" type="FieldsType"/>
            <xs:element name="MasterSource" type="MasterSourceType" minOccurs="0"/>
            <xs:element name="Index" type="IndexType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="extends" type="xs:string" use="required"/>
        <xs:attribute name="abstract" type="xs:boolean"/>
        <xs:attribute name="tableName" type="xs:string"/>
        <xs:attribute name="database" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="FieldsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="FieldBoolean" type="FieldBooleanType"/>
            <xs:element name="FieldDate" type="FieldDateType"/>
            <xs:element name="FieldDouble" type="FieldDoubleType"/>
            <xs:element name="FieldInteger" type="FieldIntegerType"/>
            <xs:element name="FieldLong" type="FieldBaseType"/>
            <xs:element name="FieldTableField" type="FieldTableFieldType"/>
            <xs:element name="FieldString" type="FieldStringType"/>
            <xs:element name="FieldBinary" type="FieldBaseType"/>
        </xs:choice>
        <xs:attribute name="primaryKeyField" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="FieldBaseType">
        <xs:all minOccurs="0">
            <xs:element name="newValue" type="newValueType" minOccurs="0"/>
            <xs:element name="validValues" type="validValuesType" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="calculated" type="xs:boolean"/>
        <xs:attribute name="calcInline" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="FieldBooleanType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FieldDateType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FieldDoubleType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FieldIntegerType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FieldTableFieldType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
                <xs:attribute name="class" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FieldStringType">
        <xs:complexContent>
            <xs:extension base="FieldBaseType">
                <xs:attribute name="size" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="newValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="IndexType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="masterKeyField" type="xs:string"/>
        <xs:attribute name="keyField" type="xs:string" use="required"/>
        <xs:attribute name="unique" type="xs:boolean"/>
        <xs:attribute name="descending" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="MasterSourceType">
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="field" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="validValuesType">
        <xs:sequence>
            <xs:element name="keyValue" type="validValueType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="validValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== tfonrouge/MOODB/src/tech/fonrouge/test/data/Person.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table abstract="true" extends="Base"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:oons="http://fonrouge.tech/MOODB"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldString name="name" description="Name" required="true"/>
        <oons:FieldString name="firstName" description="First name" required="true"/>
        <oons:FieldString name="lastName" description="Last name"/>
        <oons:FieldDate name="bday" description="Birth day"/>
        <oons:FieldString name="gender" required="true">
            <oons:validValues>
                <oons:keyValue key="M">Male</oons:keyValue>
                <oons:keyValue key="F">Female</oons:keyValue>
                <oons:keyValue key="?">Undetermined</oons:keyValue>
            </oons:validValues>
        </oons:FieldString>
        <oons:FieldBoolean name="married"/>
        <oons:FieldString name="personId" description="Person Id"/>

    </oons:Fields>

    <oons:Index name="personId" keyField="personId" unique="true"/>

</oons:Table>

=== tfonrouge/MOODB/Test/src/test01/data/invoiceItem/InvoiceItem.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oons="http://fonrouge.tech/MOODB"
            extends="Base01"
            tableName="invoiceItem"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldTableField name="invoice" class="Invoice" description="Invoice" required="true"/>
        <oons:FieldTableField name="invItem" class="Inventory" required="true"/>
        <oons:FieldDouble name="qty" description="Quantity" required="true"/>
        <oons:FieldDouble name="unitPrice" description="Unit Price" required="true"/>

        <oons:FieldDouble name="total" calculated="true"/>

    </oons:Fields>

    <oons:Index name="date" keyField="date"/>

</oons:Table>

=== tfonrouge/MOODB/src/tech/fonrouge/test/data/User.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table extends="Person" tableName="users"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:oons="http://fonrouge.tech/MOODB"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldString name="userId" description="User Id" required="true"/>
        <oons:FieldString name="userLevel" description="User level">
            <oons:validValues>
                <oons:keyValue key="0">General user</oons:keyValue>
                <oons:keyValue key="1">Admin user</oons:keyValue>
            </oons:validValues>
        </oons:FieldString>
        <oons:FieldString name="password" description="User password" required="true"/>
        <oons:FieldDate name="lastLogin" description="Last date login"/>
        <oons:FieldInteger name="logCounter" description="Login counter"/>

    </oons:Fields>

    <oons:Index name="userId" keyField="userId" unique="true"/>

</oons:Table>

=== tfonrouge/MOODB/Test/src/test01/data/entity/Entity.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oons="http://fonrouge.tech/MOODB"
            abstract="true"
            extends="TableBase"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldString name="name" description="Name" required="true"/>
        <oons:FieldString name="taxId" description="Tax payer id" required="true"/>
        <oons:FieldString name="country" description="Country id"/>
        <oons:FieldString name="address"/>
        <oons:FieldString name="phone1"/>
        <oons:FieldString name="phone2"/>
        <oons:FieldString name="phone3"/>
        <oons:FieldString name="webPage"/>
        <oons:FieldString name="email1"/>
        <oons:FieldString name="email2"/>
        <oons:FieldString name="email3"/>

    </oons:Fields>

    <oons:Index name="taxId" keyField="taxId" unique="true"/>

</oons:Table>

=== tfonrouge/MOODB/Test/src/test01/data/user/User.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oons="http://fonrouge.tech/MOODB"
            extends="Person"
            tableName="users"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldString name="userId" description="User Id" required="true"/>
        <oons:FieldString name="userLevel" description="User level">
            <oons:validValues>
                <oons:value label="General User">"0"</oons:value>
                <oons:value label="Admin User">"1"</oons:value>
            </oons:validValues>
        </oons:FieldString>
        <oons:FieldString name="password" description="User password" required="true"/>
        <oons:FieldDate name="lastLogin" description="Last date login"/>
        <oons:FieldInteger name="logCounter" description="Login counter"/>

    </oons:Fields>

    <oons:Index name="userId" keyField="userId" unique="true"/>

</oons:Table>

=== tfonrouge/MOODB/Test/src/test01/data/Inventory.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table extends="Base" tableName="inventory"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:oons="http://fonrouge.tech/MOODB"
            xsi:noNamespaceSchemaLocation="/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldString name="itemId" description="Inventory Item Id" required="true"/>
        <oons:FieldString name="name" description="name" required="true"/>
        <oons:FieldString name="uom" description="Unit of measure" required="true"/>
        <oons:FieldDouble name="stock" description="Stock"/>
        <oons:FieldDouble name="unitPrice" description="Unit price" required="true"/>
        <oons:FieldDate name="date" calculated="true"/>
        <oons:FieldBinary name="image"/>

    </oons:Fields>

    <oons:Index name="itemId" keyField="itemId" unique="true"/>
    <oons:Index name="name" keyField="name"/>

</oons:Table>

=== tfonrouge/MOODB/Test/src/test01/data/invoice/Invoice.xml
<?xml version="1.0" encoding="utf-8" ?>

<oons:Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oons="http://fonrouge.tech/MOODB"
            extends="TableBase"
            tableName="invoice"
            xsi:schemaLocation="http://fonrouge.tech/MOODB http://fonrouge.tech/MOODB/moodbxml.xsd">

    <oons:Fields>

        <oons:FieldInteger name="docNumber" description="Invoice number" autoInc="true"/>
        <oons:FieldTableField name="customer" class="Customer" notNull="true"/>
        <oons:FieldDate name="date" notNull="true"/>
        <oons:FieldInteger name="daysOfCredit" notNull="true"/>
        <oons:FieldLong name="itemsCount" calculated="true"/>
        <oons:FieldBoolean name="reqShipment" notNull="true"/>
        <oons:FieldDouble name="deliveryCost" notNull="true"/>

    </oons:Fields>

    <oons:Index name="docNumber" keyField="docNumber" unique="true"/>

</oons:Table>
